version: '3.9'

services:
  # Vue.js application service
  vuejs-app:
    build: .
    ports:
      - "8080:80"

  # Nginx service
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./vue-app:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vuejs-app
